#!/usr/bin/env bash
set -euo pipefail

PROJECT_NAME="${NUTRAPASS_PAGES_PROJECT:-nutrapass-widget}"
BRANCH="${NUTRAPASS_PAGES_BRANCH:-main}"
ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
STAGE_DIR="${NUTRAPASS_WIDGET_STAGE_DIR:-$ROOT_DIR/.pages-deploy}"
RUN_TESTS=1
DEPLOY=1

usage() {
  cat <<'USAGE'
Usage: scripts/deploy-widget.sh [--stage-only] [--skip-tests]

Stages the NutraPass static widget into a clean Cloudflare Pages deploy folder,
runs the regression tests by default, then deploys only the public widget files.

Options:
  --stage-only   Build/list the clean deploy folder without calling Cloudflare.
  --skip-tests   Deploy without running npm test first.

Environment overrides:
  NUTRAPASS_PAGES_PROJECT   Cloudflare Pages project name (default: nutrapass-widget)
  NUTRAPASS_PAGES_BRANCH    Cloudflare Pages branch (default: main)
  NUTRAPASS_WIDGET_STAGE_DIR staging folder (default: .pages-deploy)
  CLOUDFLARE_API_TOKEN      required for non-interactive deploys
USAGE
}

for arg in "$@"; do
  case "$arg" in
    --stage-only) DEPLOY=0 ;;
    --skip-tests) RUN_TESTS=0 ;;
    -h|--help) usage; exit 0 ;;
    *) echo "Unknown argument: $arg" >&2; usage; exit 2 ;;
  esac
done

cd "$ROOT_DIR"

if [[ $RUN_TESTS -eq 1 ]]; then
  echo "==> Running NutraPass regression tests"
  npm test
fi

echo "==> Staging clean Pages artifact: $STAGE_DIR"
rm -rf "$STAGE_DIR"
mkdir -p "$STAGE_DIR/Art"

cp "$ROOT_DIR/index.html" "$STAGE_DIR/index.html"
cp "$ROOT_DIR/Art/nutrapass-logo-horizontal-leaf-black.png" "$STAGE_DIR/Art/"
cp "$ROOT_DIR/Art/nutrapass-botanical-strip.png" "$STAGE_DIR/Art/"

cat > "$STAGE_DIR/README-deploy-artifact.txt" <<'README'
This folder is generated by scripts/deploy-widget.sh.
It intentionally contains only the public NutraPass widget files for Cloudflare Pages.
Do not edit this folder directly; edit the project source files instead.
README

echo "==> Files staged for deploy"
find "$STAGE_DIR" -maxdepth 2 -type f -printf '  %P\n' | sort

if [[ $DEPLOY -eq 0 ]]; then
  echo "==> Stage-only mode complete. No Cloudflare deploy attempted."
  exit 0
fi

if [[ -z "${CLOUDFLARE_API_TOKEN:-}" ]]; then
  echo "ERROR: CLOUDFLARE_API_TOKEN is not set, so Wrangler cannot deploy non-interactively." >&2
  echo "Set it in the Hermes environment, then restart the gateway, or run wrangler login locally." >&2
  exit 1
fi

echo "==> Deploying to Cloudflare Pages project '$PROJECT_NAME' on branch '$BRANCH'"
# Run Wrangler from the clean staged artifact directory. This avoids writing
# .wrangler/tmp under synced project folders that may have restrictive perms.
npx --yes wrangler@latest pages deploy . --cwd "$STAGE_DIR" --project-name "$PROJECT_NAME" --branch "$BRANCH" --commit-dirty=true

echo "==> Deployment command completed. Verify production URL: https://${PROJECT_NAME}.pages.dev"
